### ISSUE TITLE
main.py，line94可能存在问题 

### ISSUE THREAD

**Issue by ryanxingql** [yangle15/RANet-pytorch#4]
首先感谢您的简洁漂亮的代码！
line94判断条件包括了(epoch==299)。本人用CIFAR-10训练发现，最佳结果94.02出现在epoch 277。
但训练结束后，界面会出现：
![image](https://user-images.githubusercontent.com/34084019/80127621-2db45300-85c7-11ea-8a99-a0caaaf0621c.png)
可能是错误的信息提示哈~

**Comment by 90651698** [comment]
您好，您有用ImageNet训练吗，训练的权重有吗？

**Comment by ryanxingql** [comment]
> 您好，您有用ImageNet训练吗，训练的权重有吗？

您好，没有哈，我只用了cifar

**Comment by 90651698** [comment]
好滴谢谢您
